// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMEventItemEx","status":true,"description":"アイテム選択の処理にヘルプウィンドウを追加し、\n個数表示の有無と表示行数をアイテムタイプごとに設定できます。","parameters":{"helpWindowEnabledItem":"1","helpWindowEnabledKey":"1","helpWindowEnabledA":"1","helpWindowEnabledB":"1","showItemNumberItem":"1","showItemNumberKey":"1","showItemNumberA":"0","showItemNumberB":"1","numVisibleRowsItem":"4","numVisibleRowsKey":"4","numVisibleRowsA":"4","numVisibleRowsB":"4","fixPlacement":"top"}},
{"name":"111_InputForm","status":true,"description":"ゲーム画面上にHTMLの入力フォームを表示します","parameters":{"OK Button Text":"決定","Display Cancel Button":"1","Cancel Button Text":"キャンセル","Judge Switch Interval":"100","Switch ID Selected OK":"0","Force OK Switch ID":"0","Force Cancel Switch ID":"0"}},
{"name":"UTSU_ChangeActorImageSystem","status":true,"description":"アクターの画像を変えます","parameters":{"読み込むファイル名":"Actor","説明ウィンドウの文字":"の画像を選択してください。","ページウィンドウの表記":"ページ","文字色の指定":"0","ウィンドウスキンの指定":"Window","ウィンドウの透明度の指定":"180","背景のファイル名":"","背景の色":"","1ページに表示する画像数":"8","SVアクター使用":"true","キャンセルコマンドの表示":"false","キャンセルの文字列":"戻る"}},
{"name":"FixClassChangeSkill","status":true,"description":"職業の変更によるスキル習得プラグイン","parameters":{"invalidSwitchId":"0"}}
];
